export const flightData = [{
    id: 1,
    name: "KLM",
    code: "KM",
    destinationCity: "Berlin",
    destinationCountry: "Germany",
    departureCity: "Amsterdam",
    departureCountry: "Netherland",
    price: {economy: 234, premium: 500, business: 700},
    imageUrl: "https://tinyurl.com/2p8f8ers",
    flightCode: 134,
    aircraft: "Airbus A220",
    departureTime: "12:30",
    arrivalTime: "16:30",
    departure: "Schiphol International Airport, Terminal I",
    arrival: "Berlin Bradenburg Airport Terminal II",
    travelTime: 4 
},

{
    id: 2,
    name: "Lufthansa",
    code: "LH",
    destinationCity: "Lagos",
    destinationCountry: "Nigeria",
    departureCity: "Frankfurt",
    departureCountry: "Germany",
    price: {economy: 734, premium: 1500, business: 1700},
    imageUrl: "https://tinyurl.com/yckun8mf",
    flightCode: 234,
    aircraft: "Boeing 727",
    departureTime: "10:30",
    arrivalTime: "16:30",
    departure: "Frankfurt International Airport, Terminal I",
    arrival: "Mutala Muhammed International Airport,  Terminal II",
    travelTime: 6 
},

{
    id: 3,
    name: "EasyJet",
    code: "EJ",
    destinationCity: "London",
    destinationCountry: "United Kindgom",
    departureCity: "Berlin",
    departureCountry: "Germany",
    price: {economy: 34, premium: 150, business: 170},
    imageUrl: "https://tinyurl.com/2p8wawvd",
    flightCode: 334,
    aircraft: "Airbus A340",
    departureTime: "08:30",
    arrivalTime: "12:30",
    departure: "Berlin Brandenburg Airport, Terminal I",
    arrival: "Heathrow International Airport,  Terminal II",
    travelTime: 6 
},

{
    id: 4,
    name: "Delta Airline",
    code: "DA",
    destinationCity: "New York",
    destinationCountry: "USA",
    departureCity: "Munich",
    departureCountry: "Germany",
    price: {economy: 334, premium: 1250, business: 1720},
    imageUrl: "https://tinyurl.com/5ayc6p53",
    flightCode: 434,
    aircraft: "Boeing 737",
    departureTime: "07:30",
    arrivalTime: "17:30",
    departure: "Munich International Airport, Terminal I",
    arrival: "John Kennedy International Airport,  Terminal II",
    travelTime: 6 
},
{
    id: 5,
    name: "Ryain Air",
    code: "RA",
    destinationCity: "Dublin",
    destinationCountry: "Ireland",
    departureCity: "Munich",
    departureCountry: "Germany",
    price: {economy: 33, premium: 125, business: 172},
    imageUrl: "https://tinyurl.com/mr3e6rf5",
    flightCode: 534,
    aircraft: "Airbus A340",
    departureTime: "07:30",
    arrivalTime: "11:30",
    departure: "Munich International Airport, Terminal I",
    arrival: "Dublin  International Airport,  Terminal II",
    travelTime: 6 
},
{
    id: 6,
    name: "KLM",
    code: "KM",
    destinationCity: "Berlin",
    destinationCountry: "Germany",
    departureCity: "Amsterdam",
    departureCountry: "Netherland",
    price: {economy: 134, premium: 600, business: 900},
    imageUrl: "https://tinyurl.com/2p8f8ers",
    flightCode: 634,
    aircraft: "Airbus A220",
    departureTime: "16:30",
    arrivalTime: "20:30",
    departure: "Schiphol International Airport, Terminal I",
    arrival: "Berlin Bradenburg Airport Terminal II",
    travelTime: 4 
},

{
    id: 7,
    name: "Lufthansa",
    code: "LH",
    destinationCity: "Lagos",
    destinationCountry: "Nigeria",
    departureCity: "Frankfurt",
    departureCountry: "Germany",
    price: {economy: 434, premium: 1200, business: 1300},
    imageUrl: "https://tinyurl.com/yckun8mf",
    flightCode: 734,
    aircraft: "Boeing 727",
    departureTime: "17:30",
    arrivalTime: "22:30",
    departure: "Frankfurt International Airport, Terminal I",
    arrival: "Mutala Muhammed International Airport,  Terminal II",
    travelTime: 6 
},

{
    id: 8,
    name: "EasyJet",
    code: "EJ",
    destinationCity: "London",
    destinationCountry: "United Kindgom",
    departureCity: "Berlin",
    departureCountry: "Germany",
    price: {economy: 24, premium: 130, business: 150},
    imageUrl: "https://tinyurl.com/2p8wawvd",
    flightCode: 834,
    aircraft: "Airbus A340",
    departureTime: "14:30",
    arrivalTime: "16:30",
    departure: "Berlin Brandenburg Airport, Terminal I",
    arrival: "Heathrow International Airport,  Terminal II",
    travelTime: 6 
},

{
    id: 9,
    name: "Delta Airline",
    code: "DA",
    destinationCity: "New York",
    destinationCountry: "USA",
    departureCity: "Munich",
    departureCountry: "Germany",
    price: {economy: 434, premium: 2250, business: 3720},
    imageUrl: "https://tinyurl.com/5ayc6p53",
    flightCode: 934,
    aircraft: "Boeing 737",
    departureTime: "12:30",
    arrivalTime: "20:30",
    departure: "Munich International Airport, Terminal I",
    arrival: "John Kennedy International Airport,  Terminal II",
    travelTime: 6 
},
{
    id: 10,
    name: "Ryain Air",
    code: "RA",
    destinationCity: "Dublin",
    destinationCountry: "Ireland",
    departureCity: "Munich",
    departureCountry: "Germany",
    price: {economy: 53, premium: 155, business: 572},
    imageUrl: "https://tinyurl.com/mr3e6rf5",
    flightCode: 1034,
    aircraft: "Airbus A340",
    departureTime: "15:30",
    arrivalTime: "18:30",
    departure: "Munich International Airport, Terminal I",
    arrival: "Dublin  International Airport,  Terminal II",
    travelTime: 6 
},
{
    id: 11,
    name: "KLM",
    code: "KM",
    destinationCity: "Amsterdam",
    destinationCountry: "Netherland",
    departureCity: "Berlin",
    departureCountry: "Germany",
    price: {economy: 234, premium: 500, business: 700},
    imageUrl: "https://tinyurl.com/2p8f8ers",
    flightCode: 1134,
    aircraft: "Airbus A220",
    departureTime: "12:30",
    arrivalTime: "16:30",
    departure: "Berlin Bradenburg Airport Terminal II ",
    arrival: "Schiphol International Airport, Terminal I",
    travelTime: 4 
},

{
    id: 12,
    name: "Lufthansa",
    code: "LH",
    destinationCity: "Frankfurt",
    destinationCountry: "Germany",
    departureCity: "Lagos",
    departureCountry: "Nigeria",
    price: {economy: 734, premium: 1500, business: 1700},
    imageUrl: "https://tinyurl.com/yckun8mf",
    flightCode: 1234,
    aircraft: "Boeing 727",
    departureTime: "10:30",
    arrivalTime: "16:30",
    departure: "Murtala Muhammed International Airport,  Terminal II",
    arrival: "Frankfurt International Airport, Terminal I",
    travelTime: 6 
},

{
    id: 13,
    name: "EasyJet",
    code: "EJ",
    destinationCity: "Berlin",
    destinationCountry: "Germany",
    departureCity: "London",
    departureCountry: "United Kingdom",
    price: {economy: 34, premium: 150, business: 170},
    imageUrl: "https://tinyurl.com/2p8wawvd",
    flightCode: 1334,
    aircraft: "Airbus A340",
    departureTime: "08:30",
    arrivalTime: "12:30",
    departure:  "Heathrow International Airport,  Terminal II",
    arrival: "Berlin Brandenburg Airport, Terminal I",
    travelTime: 6 
},

{
    id: 14,
    name: "Delta Airline",
    code: "DA",
    destinationCity: "Munich",
    destinationCountry: "Germany",
    departureCity: "New York",
    departureCountry: "USA",
    price: {economy: 334, premium: 1250, business: 1720},
    imageUrl: "https://tinyurl.com/5ayc6p53",
    flightCode: 1434,
    aircraft: "Boeing 737",
    departureTime: "07:30",
    arrivalTime: "17:30",
    departure: "John Kennedy International Airport,  Terminal II",
    arrival: "Munich International Airport, Terminal I",
    travelTime: 6 
},
{
    id: 15,
    name: "Ryain Air",
    code: "RA",
    destinationCity: "Munich",
    destinationCountry: "Germany",
    departureCity: "Dublin",
    departureCountry: "Ireland",
    price: {economy: 33, premium: 125, business: 172},
    imageUrl: "https://tinyurl.com/mr3e6rf5",
    flightCode: 1534,
    aircraft: "Airbus A340",
    departureTime: "07:30",
    arrivalTime: "11:30",
    departure: "Dublin  International Airport,  Terminal II",
    arrival: "Munich International Airport, Terminal I", 
    travelTime: 6 
},
{
    id: 16,
    name: "Polish Airline",
    code: "PA",
    destinationCity: "Warsaw",
    destinationCountry: "Poland",
    departureCity: "Leipzig",
    departureCountry: "Germany",
    price: {economy: 33, premium: 125, business: 172},
    imageUrl: "https://tinyurl.com/38hfjfcc",
    flightCode: 1634,
    aircraft: "Airbus A340",
    departureTime: "07:30",
    arrivalTime: "11:30",
    departure: "Poland  International Airport,  Terminal II",
    arrival: "Leipzig International Airport, Terminal I", 
    travelTime: 6 
},
{
    id: 17,
    name: "Polish Airline",
    code: "PA",
    destinationCity: "Leipzig",
    destinationCountry: "Germany",
    departureCity: "Warsaw",
    departureCountry: "Poland",
    price: {economy: 33, premium: 125, business: 172},
    imageUrl: "https://tinyurl.com/38hfjfcc",
    flightCode: 1734,
    aircraft: "Airbus A340",
    departureTime: "07:30",
    arrivalTime: "11:30",
    departure: "Leipzig  International Airport,  Terminal II",
    arrival: "Poland International Airport, Terminal I", 
    travelTime: 6 
},
{
    id: 18,
    name: "Austrian Air",
    code: "AA",
    destinationCity: "Vienna",
    destinationCountry: "Austria",
    departureCity: "Paris",
    departureCountry: "France",
    price: {economy: 33, premium: 125, business: 172},
    imageUrl: "https://tinyurl.com/49c9mt8p",
    flightCode: 1834,
    aircraft: "Airbus A340",
    departureTime: "07:30",
    arrivalTime: "11:30",
    departure: "Vienna  International Airport,  Terminal II",
    arrival: "Paris International Airport, Terminal I", 
    travelTime: 6 
},
{
    id: 19,
    name: "Austrian Air",
    code: "AA",
    destinationCity: "Paris",
    destinationCountry: "France",
    departureCity: "Vienna",
    departureCountry: "Austria",
    price: {economy: 33, premium: 125, business: 172},
    imageUrl: "https://tinyurl.com/38hfjfcc",
    flightCode: 1934,
    aircraft: "Airbus A340",
    departureTime: "07:30",
    arrivalTime: "11:30",
    departure: "Paris  International Airport,  Terminal II",
    arrival: "Vienna International Airport, Terminal I", 
    travelTime: 6 
},
{
    id: 20,
    name: "Azul Brazilian Airline",
    code: "AB",
    destinationCity: "Rio de Janeiro",
    destinationCountry: "Brazil",
    departureCity: "Sydney",
    departureCountry: "Australia",
    price: {economy: 33, premium: 125, business: 172},
    imageUrl: "https://tinyurl.com/2nv9n7dj",
    flightCode: 2012,
    aircraft: "Airbus A340",
    departureTime: "07:30",
    arrivalTime: "11:30",
    departure: "Sydney  International Airport,  Terminal II",
    arrival: "Rio de Janeiro International Airport, Terminal I", 
    travelTime: 6 
},
{
    id: 21,
    name: "Azul Brazilian Airline",
    code: "AB",
    destinationCity: "Sydney",
    destinationCountry: "Australia",
    departureCity: "Rio de Janeiro",
    departureCountry: "Brazil",
    price: {economy: 33, premium: 125, business: 172},
    imageUrl: "https://tinyurl.com/2nv9n7dj",
    flightCode: 2112,
    aircraft: "Airbus A340",
    departureTime: "07:30",
    arrivalTime: "11:30",
    departure: "Rio de Janeiro  International Airport,  Terminal II",
    arrival: "Sydney International Airport, Terminal I", 
    travelTime: 6 
},




]